version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - NODE_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - temporal

  temporal:
    image: temporalio/auto-setup:1.23
    environment:
      - DB=sqlite
      - TEMPORAL_UI_PORT=8088
    ports:
      - "7233:7233"
      - "8088:8088"
