log:
  stdout: true
  level: "info"

persistence:
  defaultStore: default
  visibilityStore: visibility
  datastores:
    default:
      sql:
        pluginName: "postgres"
        databaseName: "temporal"
        connectAddr: "postgres:5432"
        user: "temporal"
        password: "temporal"
        maxConns: 20
        maxIdleConns: 20
        connMaxLifetime: 1h
    visibility:
      sql:
        pluginName: "postgres"
        databaseName: "temporal_visibility"
        connectAddr: "postgres:5432"
        user: "temporal"
        password: "temporal"
        maxConns: 20
        maxIdleConns: 20
        connMaxLifetime: 1h

global:
  membership:
    maxJoinDuration: 30s
    broadcastAddress: 0.0.0.0

services:
  frontend:
    rpc:
      port: 7233
  matching:
    rpc:
      port: 7235
  history:
    rpc:
      port: 7234
  worker:
    rpc:
      port: 7239
